-- Insert sample movies
INSERT INTO public.movies (title, description, genre, year, rating, duration, director, "cast", image_url) VALUES
('Dune: Parte Dois', 'Paul Atreides une-se a Chani e aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família.', 'Ficção Científica', 2024, 8.8, '166 min', 'Denis Villeneuve', ARRAY['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson'], '/dune-inspired-poster.png'),
('Oppenheimer', 'A história de J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica durante a Segunda Guerra Mundial.', 'Drama', 2023, 8.4, '180 min', 'Christopher Nolan', ARRAY['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'], '/images/posters/oppenheimer-poster.png'),
('Homem-Aranha: Através do Aranhaverso', 'Miles Morales embarca em uma aventura épica através do multiverso com outros Homens-Aranha.', 'Animação', 2023, 8.7, '140 min', 'Joaquim Dos Santos', ARRAY['Shameik Moore', 'Hailee Steinfeld', 'Brian Tyree Henry'], '/spiderman-movie-poster.jpg'),
('Top Gun: Maverick', 'Depois de mais de 30 anos de serviço, Pete ''Maverick'' Mitchell continua sendo um dos melhores pilotos da Marinha.', 'Ação', 2022, 8.3, '130 min', 'Joseph Kosinski', ARRAY['Tom Cruise', 'Miles Teller', 'Jennifer Connelly'], '/top-gun-movie-poster.jpg'),
('Pantera Negra: Wakanda Para Sempre', 'A rainha Ramonda, Shuri, M''Baku, Okoye e as Dora Milaje lutam para proteger sua nação das potências mundiais.', 'Ação', 2022, 6.7, '161 min', 'Ryan Coogler', ARRAY['Letitia Wright', 'Angela Bassett', 'Tenoch Huerta'], '/black-panther-poster.jpg'),
('Tudo em Todo Lugar ao Mesmo Tempo', 'Uma dona de lavanderia chinesa-americana é varrida por uma aventura louca onde ela sozinha pode salvar o mundo.', 'Ficção Científica', 2022, 7.8, '139 min', 'Daniels', ARRAY['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan'], '/everything-everywhere-movie-poster.jpg'),
('Avatar: O Caminho da Água', 'Jake Sully vive com sua nova família formada no planeta de Pandora.', 'Ficção Científica', 2022, 9.2, '192 min', 'James Cameron', ARRAY['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver'], '/generic-sci-fi-poster.png'),
('The Batman', 'Quando um assassino sádico aterroriza Gotham City, Batman deve investigar a corrupção oculta e questionar a ligação de sua família com o crime organizado.', 'Ação', 2022, 8.8, '176 min', 'Matt Reeves', ARRAY['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano'], '/dark-knight-poster.png');

-- Insert sample voting sessions
INSERT INTO public.voting_sessions (title, description, start_date, end_date, status) VALUES
('Escolha o Filme do Próximo Final de Semana', 'Vote no filme que você mais quer ver na sessão especial deste sábado às 20h!', NOW() - INTERVAL '1 day', NOW() + INTERVAL '2 days', 'active'),
('Sessão de Terror - Halloween Especial', 'Filmes de terror para comemorar o Halloween', '2024-10-25 00:00:00', '2024-10-31 23:59:59', 'completed'),
('Clássicos do Cinema', 'Os grandes clássicos que marcaram a história do cinema', '2024-10-18 00:00:00', '2024-10-24 23:59:59', 'completed'),
('Filmes de Ação', 'Ação pura para os amantes de adrenalina', '2024-10-11 00:00:00', '2024-10-17 23:59:59', 'completed');

-- Insert sample blog posts
INSERT INTO public.blog_posts (title, content, excerpt, category, featured, author_id) VALUES
('A Evolução dos Efeitos Especiais no Cinema', 'Desde os primórdios do cinema até os dias atuais, os efeitos especiais revolucionaram a forma como contamos histórias na tela grande. Uma análise profunda sobre como a tecnologia transformou a indústria cinematográfica...', 'Desde os primórdios do cinema até os dias atuais, os efeitos especiais revolucionaram a forma como contamos histórias na tela grande.', 'Tecnologia', true, NULL),
('Análise: Por que ''Dune'' Conquistou o Público', 'Uma análise detalhada dos elementos que fizeram de Dune um dos maiores sucessos da ficção científica moderna. Denis Villeneuve conseguiu adaptar o impossível...', 'Uma análise detalhada dos elementos que fizeram de Dune um dos maiores sucessos da ficção científica moderna.', 'Análise', false, NULL),
('Entrevista Exclusiva com Diretor Brasileiro', 'Conversamos com um dos diretores mais promissores do cinema nacional sobre seus próximos projetos. Em uma conversa exclusiva, o diretor revela seus planos...', 'Conversamos com um dos diretores mais promissores do cinema nacional sobre seus próximos projetos.', 'Entrevista', false, NULL),
('Os Melhores Filmes de 2024 Até Agora', 'Uma seleção cuidadosa dos filmes que marcaram o primeiro semestre de 2024 e que você não pode perder. 2024 tem sido um ano excepcional para o cinema...', 'Uma seleção cuidadosa dos filmes que marcaram o primeiro semestre de 2024 e que você não pode perder.', 'Lista', false, NULL),
('Como o Cinema Independente Está Mudando', 'O cinema independente passa por uma revolução com novas plataformas e formas de distribuição. As mudanças no mercado cinematográfico...', 'O cinema independente passa por uma revolução com novas plataformas e formas de distribuição.', 'Indústria', false, NULL),
('Bastidores: Como São Feitas as Cenas de Ação', 'Um olhar por trás das câmeras para entender como são criadas as sequências de ação mais espetaculares do cinema. As cenas de ação são uma das partes mais complexas...', 'Um olhar por trás das câmeras para entender como são criadas as sequências de ação mais espetaculares do cinema.', 'Bastidores', false, NULL);
